//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDatail
    {
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string ShipAddress { get; set; }
        public short Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public string ProductName { get; set; }
        public string QuantityPerUnit { get; set; }
    }
}
